version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: fastapi-backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        container_name: react-frontend
        ports:
            - "3000:80"
        volumes:
            - ./frontend:/app
        restart: unless-stopped
# Optional: Add a network (default bridge network used unless you want something custom)
